### ISSUE TITLE
Error thrown when using plotting.plot_relationship

### ISSUE THREAD

**Issue by ff995** [arm61/uravu#22]
**Describe the bug**
Running plotting.plot_relationship throws NameError: 'colors' is not defined.

**To Reproduce**
Pasted code from 'Using Distributions' tutorial.

**Expected behavior**
A figure was created and displayed, but the graph was not plotted.

**Screenshots**
![scr](https://user-images.githubusercontent.com/70442131/91639833-2ab3ee00-ea11-11ea-8671-7f3c2613ec9a.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Python Version: 3.7.6
 - uravu Version: 1.1.0

**Comment by arm61** [comment]
Do you have `matplotlib`, `corner`, and `seaborn` installed? There should have been a statement asking you to install these then you importing the `plotting` module.

**Comment by ff995** [comment]
Thanks for responding. Installing corner and seaborn solved the problem. I don't think I got a message when I imported plotting from uravu.
![image](https://user-images.githubusercontent.com/70442131/91663687-52bf5200-eae2-11ea-9a15-e1da741c7d54.png)

**Comment by arm61** [comment]
Thanks for the issue anyway! I want to put in a fix to give an explanatory error instead of this not helpful error. So I am going to re-open this issue as a way to remind myself!

**Comment by arm61** [comment]
The functionality has been improved in [v1.1.1](https://github.com/arm61/uravu/releases/tag/1.1.1), which is now up on pypi. I'll close the issue now.
