### ISSUE TITLE
Error when importing uravu

### ISSUE THREAD

**Issue by ff9955** [arm61/uravu#26]
Hello,

It's me again, I had to create a new account after my gmail was compromised. I'm receiving an error when trying to import the new version of uravu.
![image](https://user-images.githubusercontent.com/73726314/97767846-cb5c8200-1b16-11eb-9a61-9fed974afb94.png)

**Comment by arm61** [comment]
Hey! Before I go down a rabbit hole can you make sure you have the latest version of scipy

`pip install -U scipy`

**Comment by arm61** [comment]
My colleague had the same bug and it was resolved by updating scipy. So I will close this for now. Feel free to reopen if it doesn't fix things.
