### ISSUE TITLE
Rotate the right hand side panel in the corner plot?

### ISSUE THREAD

**Issue by nvaytet** [arm61/uravu#29]
![Screenshot at 2021-02-25 10-58-21](https://user-images.githubusercontent.com/39047984/109137305-57935480-7759-11eb-92a2-b54d58fa4c07.png)

Unless i misunderstood what the panels were representing...

**Comment by arm61** [comment]
I have thought this also and to an extent I agree. 

I am using the corner package to help generate these, and I think the way it is done makes more sense for >2 parameters (see the bottom figure here https://corner.readthedocs.io/en/latest/pages/quickstart.html).
